DROP DATABASE Farm;
CREATE DATABASE Farm;
USE Farm;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50),
  password VARCHAR(255)
);

CREATE TABLE TEMP (
    id INT AUTO_INCREMENT PRIMARY KEY,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  temp FLOAT
);

CREATE TABLE HUMID (
    id INT AUTO_INCREMENT PRIMARY KEY,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  humid FLOAT
);

CREATE TABLE LIGHT (
    id INT AUTO_INCREMENT PRIMARY KEY,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  light FLOAT
);

CREATE TABLE SOIL (
    id INT AUTO_INCREMENT PRIMARY KEY,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  soil FLOAT
);

CREATE TABLE LED (
    id INT AUTO_INCREMENT PRIMARY KEY,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  led FLOAT
);

CREATE TABLE PUMP (
    id INT AUTO_INCREMENT PRIMARY KEY,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  pump FLOAT
);



CREATE TABLE LIMITED (
  id INT AUTO_INCREMENT PRIMARY KEY,
  device VARCHAR(50),
  limit_up VARCHAR(50),
  limit_down VARCHAR(50),
  time DATETIME
);
